server {
    index index.php index.html;
    server_name phpfpm.local;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/html;
    location ~ \.php$ {
        try_files $uri $uri/ =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm-ping:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location /ping4/sitemap.xml {
        rewrite /ping4/sitemap.xml /ping4/sitemap.php last;
    }

    location /ping6/sitemap.xml {
        rewrite /ping6/sitemap.xml /ping6/sitemap.php last;
    }

    location /ping4/ping {
        rewrite ^/ping4/ping/(.*)$ /ping4/index.php?host=$1 last;
    }
    location /ping4/stats {
        rewrite ^/ping4/stats/(.*)$ /ping4/stats.php?host=$1 last;
    }
}
