version: '3.9'

services:
  web:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default
    links:
      - php-fpm-ping
    environment:
      - VIRTUAL_HOST=ping4.network,ping6.network,dumpers.xyz,www.ping4.network,www.ping6.network,www.dumpers.xyz
      - LETSENCRYPT_HOST=ping4.network,ping6.network,dumpers.xyz,www.ping4.network,www.ping6.network,www.dumpers.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-ernstjason1@gmail.com}
    restart: unless-stopped

  php-fpm-ping:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./src:/var/www/html
    networks:
      - default
      - net2
    restart: unless-stopped

networks:
  default:
    external: true
    name: bridge
  net2:
    name: net2
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1
