services:
  web:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nginx-proxy
      - backend
    environment:
      - VIRTUAL_HOST=ping4.network,ping6.network,dumpers.xyz,www.ping4.network,www.ping6.network,www.dumpers.xyz
      - LETSENCRYPT_HOST=ping4.network,ping6.network,dumpers.xyz,www.ping4.network,www.ping6.network,www.dumpers.xyz
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL:-ernstjason1@gmail.com}
    restart: unless-stopped

  php-fpm-ping:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - ./src:/var/www/html
    networks:
      - backend
      - ipv6net
    restart: unless-stopped

networks:
  nginx-proxy:
    external: true
  backend:
    driver: bridge
  ipv6net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1
